apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: amq-online-infra
  name: enmasse.io:kube-state-metrics
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "watch"]
