apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: enmasse-source
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: enmasse
spec:
  displayName: EnMasse Operator Source
  image: 
  publisher: enmasse
  sourceType: grpc
