apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: enmasse-source
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: enmasse
spec:
  displayName: EnMasse Operator Source
  image: registry.redhat.io/amq7/amq-online-1-controller-manager-rhel7-operator-metadata:1.4
  publisher: enmasse
  sourceType: grpc
