apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: enmasse-sub
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: enmasse
spec:
  name: amq-online
  source: enmasse-source
  sourceNamespace: ${OPERATOR_NAMESPACE}
  startingCSV: amq-online.1.5.1
  channel: stable
