apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: enmasse
  name: addressplans.admin.enmasse.io
spec:
  conversion:
    strategy: None
  group: admin.enmasse.io
  names:
    categories:
      - enmasse
    kind: AddressPlan
    listKind: AddressPlanList
    plural: addressplans
    singular: addressplan
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The phase of the address plan
          jsonPath: .status.phase
          name: Phase
          type: string
        - description: The status of the address plan
          jsonPath: .status.message
          name: Status
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta2
      schema:
        openAPIV3Schema:
          description: AddressPlan describes the resource usage and common properties of an address. This resource is created by the service administrator.
          properties:
            addressType:
              type: string
            displayName:
              type: string
            displayOrder:
              type: integer
            longDescription:
              type: string
            requiredResources:
              items:
                properties:
                  credit:
                    type: number
                  name:
                    type: string
                required:
                  - name
                  - credit
                type: object
              type: array
            shortDescription:
              type: string
            spec:
              anyOf:
                - properties:
                    addressType:
                      pattern: (queue|topic|subscription|anycast|multicast)
                  required:
                    - addressType
                    - resources
                - properties:
                    type:
                      pattern: deadletter
                  required:
                    - addressType
              properties:
                addressType:
                  enum:
                    - queue
                    - topic
                    - subscription
                    - anycast
                    - multicast
                    - deadletter
                  type: string
                displayName:
                  type: string
                displayOrder:
                  type: integer
                longDescription:
                  type: string
                messageRedelivery:
                  description: Configures message redelivery options.  Applies to address types queue, subscription and deadletter only.
                  properties:
                    maximumDeliveryAttempts:
                      description: Maximum number of delivery attempts that will be made for a message before message is directed to a deadletter address (or dropped). Set to -1 for infinite re-deliveries.
                      type: integer
                    maximumDeliveryDelay:
                      description: The maximum delivery delay in milliseconds. Imposes an upper limit on the delivery delay.
                      type: integer
                    redeliveryDelay:
                      description: The number of milliseconds to wait before redelivery. Set to 0 for no redelivery delay.
                      type: integer
                    redeliveryDelayMultiplier:
                      description: The redelivery multiplier. This factor is applied to last redelivery delay.
                      type: number
                  type: object
                messageTtl:
                  description: Restricts message time-to-live (TTL). Applies to address types queue, topic, and deadletter only.
                  properties:
                    maximum:
                      description: Imposes a maximum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values greater than this value (or no TTL value) will have their expiration adjusted.
                      type: integer
                    minimum:
                      description: Imposes a minimum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values less than this value will have their expiration adjusted.
                      type: integer
                  type: object
                partitions:
                  type: integer
                resources:
                  properties:
                    broker:
                      type: number
                    router:
                      type: number
                  type: object
                shortDescription:
                  type: string
              type: object
            status:
              properties:
                message:
                  description: Status and error messages for the address plan.
                  type: string
                phase:
                  description: Phase of the address plan.
                  type: string
              type: object
            uuid:
              type: string
          type: object
      served: true
      storage: true
    - additionalPrinterColumns:
        - description: The phase of the address plan
          jsonPath: .status.phase
          name: Phase
          type: string
        - description: The status of the address plan
          jsonPath: .status.message
          name: Status
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          description: AddressPlan describes the resource usage and common properties of an address. This resource is created by the service administrator.
          properties:
            addressType:
              type: string
            displayName:
              type: string
            displayOrder:
              type: integer
            longDescription:
              type: string
            requiredResources:
              items:
                properties:
                  credit:
                    type: number
                  name:
                    type: string
                required:
                  - name
                  - credit
                type: object
              type: array
            shortDescription:
              type: string
            spec:
              anyOf:
                - properties:
                    addressType:
                      pattern: (queue|topic|subscription|anycast|multicast)
                  required:
                    - addressType
                    - resources
                - properties:
                    type:
                      pattern: deadletter
                  required:
                    - addressType
              properties:
                addressType:
                  enum:
                    - queue
                    - topic
                    - subscription
                    - anycast
                    - multicast
                    - deadletter
                  type: string
                displayName:
                  type: string
                displayOrder:
                  type: integer
                longDescription:
                  type: string
                messageRedelivery:
                  description: Configures message redelivery options.  Applies to address types queue, subscription and deadletter only.
                  properties:
                    maximumDeliveryAttempts:
                      description: Maximum number of delivery attempts that will be made for a message before message is directed to a deadletter address (or dropped). Set to -1 for infinite re-deliveries.
                      type: integer
                    maximumDeliveryDelay:
                      description: The maximum delivery delay in milliseconds. Imposes an upper limit on the delivery delay.
                      type: integer
                    redeliveryDelay:
                      description: The number of milliseconds to wait before redelivery. Set to 0 for no redelivery delay.
                      type: integer
                    redeliveryDelayMultiplier:
                      description: The redelivery multiplier. This factor is applied to last redelivery delay.
                      type: number
                  type: object
                messageTtl:
                  description: Restricts message time-to-live (TTL). Applies to address types queue, topic, and deadletter only.
                  properties:
                    maximum:
                      description: Imposes a maximum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values greater than this value (or no TTL value) will have their expiration adjusted.
                      type: integer
                    minimum:
                      description: Imposes a minimum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values less than this value will have their expiration adjusted.
                      type: integer
                  type: object
                partitions:
                  type: integer
                resources:
                  properties:
                    broker:
                      type: number
                    router:
                      type: number
                  type: object
                shortDescription:
                  type: string
              type: object
            status:
              properties:
                message:
                  description: Status and error messages for the address plan.
                  type: string
                phase:
                  description: Phase of the address plan.
                  type: string
              type: object
            uuid:
              type: string
          type: object
      served: true
      storage: false
    - additionalPrinterColumns:
        - description: The phase of the address plan
          jsonPath: .status.phase
          name: Phase
          type: string
        - description: The status of the address plan
          jsonPath: .status.message
          name: Status
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: AddressPlan describes the resource usage and common properties of an address. This resource is created by the service administrator.
          properties:
            addressType:
              type: string
            displayName:
              type: string
            displayOrder:
              type: integer
            longDescription:
              type: string
            requiredResources:
              items:
                properties:
                  credit:
                    type: number
                  name:
                    type: string
                required:
                  - name
                  - credit
                type: object
              type: array
            shortDescription:
              type: string
            spec:
              anyOf:
                - properties:
                    addressType:
                      pattern: (queue|topic|subscription|anycast|multicast)
                  required:
                    - addressType
                    - resources
                - properties:
                    type:
                      pattern: deadletter
                  required:
                    - addressType
              properties:
                addressType:
                  enum:
                    - queue
                    - topic
                    - subscription
                    - anycast
                    - multicast
                    - deadletter
                  type: string
                displayName:
                  type: string
                displayOrder:
                  type: integer
                longDescription:
                  type: string
                messageRedelivery:
                  description: Configures message redelivery options.  Applies to address types queue, subscription and deadletter only.
                  properties:
                    maximumDeliveryAttempts:
                      description: Maximum number of delivery attempts that will be made for a message before message is directed to a deadletter address (or dropped). Set to -1 for infinite re-deliveries.
                      type: integer
                    maximumDeliveryDelay:
                      description: The maximum delivery delay in milliseconds. Imposes an upper limit on the delivery delay.
                      type: integer
                    redeliveryDelay:
                      description: The number of milliseconds to wait before redelivery. Set to 0 for no redelivery delay.
                      type: integer
                    redeliveryDelayMultiplier:
                      description: The redelivery multiplier. This factor is applied to last redelivery delay.
                      type: number
                  type: object
                messageTtl:
                  description: Restricts message time-to-live (TTL). Applies to address types queue, topic, and deadletter only.
                  properties:
                    maximum:
                      description: Imposes a maximum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values greater than this value (or no TTL value) will have their expiration adjusted.
                      type: integer
                    minimum:
                      description: Imposes a minimum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values less than this value will have their expiration adjusted.
                      type: integer
                  type: object
                partitions:
                  type: integer
                resources:
                  properties:
                    broker:
                      type: number
                    router:
                      type: number
                  type: object
                shortDescription:
                  type: string
              type: object
            status:
              properties:
                message:
                  description: Status and error messages for the address plan.
                  type: string
                phase:
                  description: Phase of the address plan.
                  type: string
              type: object
            uuid:
              type: string
          type: object
      served: true
      storage: false
