apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:address-space-controller-amq-online-infra"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:address-space-controller
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: amq-online-infra
