---
- name: Create project namespace
  shell: oc new-project {{ monitoring_namespace }} --description="EnMasse Monitoring"
  register: namespace_exists
  failed_when: namespace_exists.stderr != '' and 'already exists' not in namespace_exists.stderr
  changed_when: namespace_exists.rc == 0

- name: Select monitoring namespace
  shell: oc project {{ monitoring_namespace }}

- name: Deploy the Application Monitoring Operator
  shell: oc apply -n {{ monitoring_namespace }} -f {{ playbook_dir }}/install/monitoring-operator

- name: ServiceMonitors crd is installed and kube-state-metrics can be installed
  shell: oc auth can-i create prometheus -n {{ monitoring_namespace }} --as system:serviceaccount:{{ monitoring_namespace }}:application-monitoring-operator
  register: permissions
  until: permissions.stdout == "yes"
  retries: 10
  delay: 5

- name: Deploy the Application Monitoring Operator
  shell: oc apply -n {{ monitoring_namespace }} -f {{ playbook_dir }}/install/monitoring-deployment

- name: Deploy Kube-state-metrics
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/install/kube-state-metrics