apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-standard-multicast
  labels:
    type: address-plan
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "standard-multicast"
      },
      "displayName": "Standard",
      "displayOrder": 0,
      "shortDescription": "Creates a direct multicast address.",
      "longDescription": "Creates a direct multicast address where messages go via a router that does not take ownership of the messages.",
      "uuid": "60fc2702-0503-11e8-b60e-507b9def37d9",
      "addressType": "multicast",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        }
      ]
    }
