apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-definition-broker
  labels:
    type: resource-definition
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "ResourceDefinition",
      "metadata": {
        "name": "broker"
      },
      "template": "queue-persisted"
    }
