apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-brokered-queue
  labels:
    type: address-plan
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "brokered-queue"
      },
      "displayName": "Brokered Queue",
      "displayOrder": 0,
      "shortDescription": "Creates a queue on a broker.",
      "longDescription": "Creates a queue on a broker.",
      "uuid": "69f82df8-0501-11e8-a0a8-507b9def37d9",
      "addressType": "queue",
      "requiredResources": [
        {
          "name": "broker",
          "credit": 0.0
        }
      ]
    }
