apiVersion: v1
data:
  config.yaml: '{"hostPort": "127.0.0.1:1099", "rules": [{"labels": {"broker":
    "$1"}, "name": "artemis_connection_count", "pattern": "org.apache.activemq.artemis<broker=\"(.+)\"><>ConnectionCount",
    "type": "GAUGE"}, {"labels": {"address": "$2", "broker": "$1"}, "name": "artemis_consumer_count",
    "pattern": "org.apache.activemq.artemis<broker=\"(.+)\", component=addresses,
    address=\"(.+)\".*><>ConsumerCount", "type": "GAUGE"}, {"labels": {"address":
    "$2", "broker": "$1"}, "name": "artemis_message_count", "pattern": "org.apache.activemq.artemis<broker=\"(.+)\",
    component=addresses, address=\"(.+)\".*><>MessageCount", "type": "GAUGE"}],
    "ssl": true}'
kind: ConfigMap
metadata:
  labels:
    app: enmasse
  name: broker-prometheus-config
