apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: brokeredinfraconfigs.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: BrokeredInfraConfig
    listKind: BrokeredInfraConfigList
    singular: brokeredinfraconfig
    plural: brokeredinfraconfigs
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - version
          properties:
            version:
              type: string
            admin:
              type: object
              properties:
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
            broker:
              type: object
              properties:
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
                    storage:
                      type: string
                addressFullPolicy:
                  type: string
                  enum:
                  - PAGE
                  - BLOCK
                  - FAIL
