apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: enmasse
  name: enmasse.io:api-server
rules:
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addresses", "addressspaces" ]
    verbs: [ "create", "get", "update", "delete", "list", "watch", "patch" ]
  - apiGroups: [ "user.enmasse.io" ]
    resources: [ "messagingusers" ]
    verbs: [ "create", "get", "update", "delete", "list", "watch", "patch" ]
  - apiGroups: [ "admin.enmasse.io" ]
    resources: [ "addressspaceplans", "addressplans", "standardinfraconfigs", "brokeredinfraconfigs" ]
    verbs: [ "create", "get", "update", "delete", "list", "watch", "patch" ]
