apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:keycloak-controller
  labels:
    app: enmasse
rules:
  - apiGroups: [ "", "user.openshift.io" ]
    resources: [ "users" ]
    verbs: [ "get" ]
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addressspaces" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "oauth.openshift.io" ]
    resources: [ "oauthclients" ]
    verbs: [ "create", "get" ]
