apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:tenant-view
  labels:
    app: enmasse
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addresses", "addressspaces" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addressspaceschemas" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "user.enmasse.io" ]
    resources: [ "messagingusers" ]
    verbs: [ "get", "list" ]
