apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:api-server-amq-online-infra"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:api-server
subjects:
- kind: ServiceAccount
  name: api-server
  namespace: amq-online-infra
