apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adress-space-controller-admin-reader
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:admin-reader
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: amq-online-infra
