apiVersion: v1
kind: Service
metadata:
  name: standard-authservice
  labels:
    app: enmasse
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: standard-authservice-cert
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: keycloak
