apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  labels:
    app: enmasse
  name: v1alpha1.user.enmasse.io
spec:
  group: user.enmasse.io
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: api-server
    namespace: amq-online-infra
  version: v1alpha1
  versionPriority: 15
