kind: Deployment
apiVersion: apps/v1
metadata:
  name: enmasse-operator
  labels:
    app: enmasse
    name: enmasse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: enmasse-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: enmasse-operator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.enmasse.io/operator-infra
                    operator: In
                    values:
                      - "true"
      serviceAccountName: enmasse-operator
      containers:
      - name: controller
        image: registry.redhat.io/amq7/enmasse-controller-manager:dev
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "enmasse-operator"
        - name: ENMASSE_DEFAULT_PULL_POLICY
          value: "Always"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        - name: CONTROLLER_ENABLE_IOT_CONFIG
          value: "true"
        - name: CONTROLLER_ENABLE_AUTHENTICATION_SERVICE
          value: "true"
        resources:
          limits:
            memory: 128Mi
