---
- shell: oc policy can-i create clusterservicebrokers
  register: can_create
  failed_when: can_create.stdout == "no"

- shell: oc extract secret/service-broker-cert -n {{ namespace }} --keys=tls.crt --to=-
  until: secret_result.rc == 0
  retries: 10
  delay: 5
  register: secret_result

- set_fact:
    ca_bundle: "{{ secret_result.stdout }}"

- name: Register Service Broker with Service Catalog
  shell:
    cmd: |
      cat <<EOF | oc apply -f -
      apiVersion: servicecatalog.k8s.io/v1beta1
      kind: ClusterServiceBroker
      metadata:
        name: enmasse
        labels:
          app: enmasse
      spec:
        url: "https://service-broker.{{ namespace }}.svc:8443/osbapi/"
        authInfo:
          bearer:
            secretRef:
              name: service-catalog-credentials
              namespace: "{{ namespace }}"
        caBundle: "{{ ca_bundle | b64encode }}"
      EOF
