apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: enmasse
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: api-server-cert
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    component: api-server
  type: ClusterIP
