kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-operator
  labels:
    app: enmasse
    name: iot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: iot-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: iot-operator
    spec:
      serviceAccountName: iot-operator
      containers:
      - name: operator
        image: registry.redhat.io/amq7/enmasse-controller-manager:dev
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "iot-operator"
        - name: ENMASSE_DEFAULT_PULL_POLICY
          value: "Always"
        - name: CONTROLLER_ENABLE_IOT_PROJECT
          value: "true"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        resources:
          limits:
            memory: 128Mi
