apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enmasse
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: prometheus
  template:
    metadata:
      labels:
        app: enmasse
        name: prometheus
    spec:
      containers:
      - image: prom/prometheus:v2.4.3
        name: prometheus
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
          readOnly: true
        - mountPath: /prometheus
          name: prometheus-data
          readOnly: false
      serviceAccountName: prometheus-server
      volumes:
      - configMap:
          name: prometheus-config
        name: prometheus-config
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data
