LOCAL_ARTIFACT_DIR:=iot/iot-device-registry-file/target/iot-device-registry-${VERSION}.jar
TECH_PREVIEW=true
REPO=amq7-tech-preview/amq-online-1-iot-device-registry-file

include ../Makefile.common

build:
