---
- name: Apply the None Authentication Service configuration
  shell:
    cmd: |
      cat <<EOF | oc apply -f -
      apiVersion: admin.enmasse.io/v1beta1
      kind: AuthenticationService
      metadata:
        name: none-authservice
        labels:
          app: enmasse
      spec:
        type: none
      EOF

