apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: enmasse
  name: grafana-config
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: direct
      url: https://prometheus-enmasse.127.0.0.1.nip.io
    - name: AlertManager
      type: camptocamp-prometheus-alertmanager-datasource
      url: https://alertmanager-enmasse.127.0.0.1.nip.io
      access: direct
      jsonData:
        timeInterval: 10s
        severity_critical: "4"
        severity_high: "3"
        severity_warning: "2"
        severity_info: "1"
      editable: true
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'EnMasse'
      org_id: 1
      folder: ''
      type: 'file'
      options:
        path: '/etc/grafana/dashboards'