LOCAL_ARTIFACT_DIR:=iot-proxy-configurator/target/iot-proxy-configurator-${VERSION}-dist.zip
TECH_PREVIEW=true
REPO=amq7-tech-preview/amq-online-1-iot-proxy-configurator

include ../Makefile.common

build:

