LOCAL_ARTIFACT_DIR:=iot/iot-lorawan-adapter/target/iot-lorawan-adapter-${VERSION}.jar
TECH_PREVIEW=true
REPO=amq7-tech-preview/amq-online-1-iot-lorawan-adapter-rhel7

include ../Makefile.common

build:
