apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: brokered-queue
  labels:
    app: enmasse
spec:
  displayName: Brokered Queue
  displayOrder: 0
  shortDescription: Creates a queue on a broker.
  longDescription: Creates a queue on a broker.
  addressType: queue
  resources:
    broker: 0.0
