apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-medium-topic
  labels:
    app: enmasse
spec:
  displayName: Medium Topic
  displayOrder: 1
  shortDescription: Creates a medium sized topic sharing underlying broker with other topics.
  longDescription: Creates a medium sized topic sharing underlying broker with other topics.
  addressType: topic
  resources:
    router: 0.01
    broker: 0.1
