apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-medium-subscription
  labels:
    app: enmasse
spec:
  displayName: Medium Subscription
  displayOrder: 1
  shortDescription: Creates a medium durable subscription on a topic.
  longDescription: Creates a medium durable subscription on a topic, which is then accessed as a distinct address.
  addressType: subscription
  resources:
    router: 0.01
    broker: 0.1
