apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: enmasse
  name: enmasse.io:service-broker
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "secrets" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "admin.enmasse.io" ]
    resources: [ "addressspaceplans", "addressplans", "standardinfraconfigs", "brokeredinfraconfigs", "authenticationservices", "consoleservices" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "", "route.openshift.io" ]
    resources: [ "routes", "routes/custom-host", "routes/status"]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
