apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "service-broker"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:service-broker
subjects:
- kind: ServiceAccount
  name: service-broker
  namespace: amq-online-infra
