apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:console-server-impersonate-amq-online-infra"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:console-server-impersonate
subjects:
- kind: ServiceAccount
  name: console-server
  namespace: amq-online-infra
