apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-definition-standard-mqtt
  labels:
    type: resource-definition
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "ResourceDefinition",
      "metadata": {
        "name": "standard-space-without-mqtt"
      },
      "template": "standard-space-infra-without-mqtt"
    }
