apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-definition-brokered
  labels:
    type: resource-definition
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "ResourceDefinition",
      "metadata": {
        "name": "brokered-space"
      },
      "template": "brokered-space-infra"
    }
