apiVersion: v1
kind: Template
metadata:
  name: address-space
  labels:
    app: enmasse
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${ADDRESS_SPACE_NAMESPACE}.${NAME}
      labels:
        type: address-space
        infraUuid: ${INFRA_UUID}
        app: enmasse
    data:
      config.json: |-
        {
          "apiVersion": "enmasse.io/v1",
          "kind": "AddressSpace",
          "metadata": {
            "name": "${NAME}",
            "namespace": "${ADDRESS_SPACE_NAMESPACE}",
            "annotations": {
              "enmasse.io/infra-uuid": "${INFRA_UUID}",
              "enmasse.io/realm-name": "${ADDRESS_SPACE_NAMESPACE}-${NAME}"
            }
          },
          "spec": {
            "type": "${TYPE}",
            "plan": "${PLAN}"
          }
        }
parameters:
  - name: NAME
    description: Name of address space
    required: true
  - name: ADDRESS_SPACE_NAMESPACE
    description: Namespace AddressSpace belongs to
    required: true
  - name: INFRA_UUID
    description: Infra uuid
    from: '[a-z]{8}'
    generate: expression
  - name: TYPE
    description: Type of address space
    required: true
  - name: PLAN
    description: Plan to use for address space
    required: true
