apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addressplans.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: AddressPlan
    listKind: AddressPlanList
    singular: addressplan
    plural: addressplans
  validation:
    openAPIV3Schema:
      properties:
        displayName:
          type: string
        displayOrder:
          type: integer
        shortDescription:
          type: string
        longDescription:
          type: string
        uuid:
          type: string
        addressType:
          type: string
        requiredResources:
          type: array
          items:
            type: object
            required:
            - name
            - credit
            properties:
              name:
                type: string
              credit:
                type: number
