apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-standard-anycast
  labels:
    type: address-plan
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "standard-anycast"
      },
      "displayName": "Standard",
      "displayOrder": 0,
      "shortDescription": "Creates a direct anycast address.",
      "longDescription": "Creates a direct anycast address where messages go via a router that does not take ownership of the messages.",
      "uuid": "45edd942-0503-11e8-84ce-507b9def37d9",
      "addressType": "anycast",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        }
      ]
    }
