apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-standard-subscription
  labels:
    type: address-plan
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "standard-subscription"
      },
      "displayName": "Topic Subscription",
      "displayOrder": 0,
      "shortDescription": "Creates a durable subscription on a topic.",
      "longDescription": "Creates a durable subscription on a topic, which is then accessed as a distinct address.",
      "uuid": "146ee531-2999-4015-85b9-a32931d7bcc5",
      "addressType": "subscription",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        },
        {
          "name": "broker",
          "credit": 0.01
        }
      ]
    }
