apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: enmasse
  name: enmasse.io:admin-reader
rules:
  - apiGroups: [ "admin.enmasse.io" ]
    resources: [ "addressplans", "addressspaceplans", "brokeredinfraconfigs", "standardinfraconfigs" ]
    verbs: [ "get", "list", "watch" ]
