apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-sharded-topic
  labels:
    type: address-plan
    app: enmasse
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "sharded-topic"
      },
      "displayName": "Sharded Topic",
      "displayOrder": 0,
      "shortDescription": "Creates a topic on a standalone broker.",
      "longDescription": "Creates a topic on a standalone broker that can be sharded.",
      "uuid": "de256d34-0502-11e8-98c9-507b9def37d9",
      "addressType": "topic",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        },
        {
          "name": "broker",
          "credit": 1.0
        }
      ]
    }
