apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: enmasse-group
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: enmasse
spec:
  targetNamespaces:
  - ${OPERATOR_NAMESPACE}