LOCAL_ARTIFACT_DIR:=iot/iot-device-registry-infinispan/target/iot-device-registry-infinispan-${VERSION}.jar
TECH_PREVIEW=true
REPO=amq7-tech-preview/amq-online-1-iot-device-registry-datagrid

include ../Makefile.common

build:
