apiVersion: v1
kind: Template
metadata:
  labels:
    app: enmasse
  name: alertmanager-config-template
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: enmasse
      name: alertmanager-config
    data:
      alertmanager.yml: |
        global:
          resolve_timeout: 5m
          smtp_smarthost: "${SMTP_SERVER}"
          smtp_from: "${SMTP_FROM_ADDRESS}"
          smtp_auth_username: "${SMTP_USERNAME}"
          smtp_auth_password: "${SMTP_PASSWORD}"
        route:
          group_by: ['alertname']
          group_wait: 60s
          group_interval: 60s
          repeat_interval: 1h
          receiver: 'sysadmins'
        receivers:
        - name: 'sysadmins'
          email_configs:
          - to: "${SYS_ADMIN_EMAIL}"
        inhibit_rules:
          - source_match:
              severity: 'critical'
            target_match:
              severity: 'warning'
            equal: ['alertname']
parameters:
  - name: SMTP_SERVER
  - name: SMTP_USERNAME
  - name: SMTP_PASSWORD
  - name: SMTP_FROM_ADDRESS
  - name: SYS_ADMIN_EMAIL