#!/usr/bin/env python

import re
import sys
for line in sys.stdin:
    m = re.search(r'Task ([0-9]+) was submitted', line)
    if m:
        sys.stdout.write(m.groups()[0] + "\n")
        sys.exit(0)
sys.stderr.write("Brew task id not found\n")
sys.exit(1)
