apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator
roleRef:
  name: grafana-operator
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: enmasse-monitoring
userNames:
  - system:serviceaccount:enmasse-monitoring:grafana-operator
