apiVersion: v1
kind: Service
metadata:
  labels:
    app: enmasse
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: none-authservice-cert
  name: none-authservice
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
  selector:
    name: none-authservice
