apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: 'middleware'
    app: enmasse
  name: kube-state-metrics
spec:
  selector:
    matchLabels:
      app: enmasse
  endpoints:
  - port: kube-metrics
  namespaceSelector:
    matchNames:
    - amq-online-infra