{
 "title": "AMQ Online",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ALERTS", "labelSelector": "*", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 7 },
   "targets": [
    { "expr": "enmasse_component_health" }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "targets": [
    { "expr": "enmasse_version" }
   ]
  },
  {
   "title": "Address Spaces",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "enmasse_address_spaces_ready_total"
    }
   ]
  },
  {
   "title": "Address Spaces Not Ready",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "expr": "enmasse_address_spaces_not_ready_total"
    }
   ]
  },
  {
   "title": "Total Addresses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "enmasse_addresses_total",
     "legendFormat": "total {{exported_namespace}}:{{addressspace}}"
    }
   ]
  },
  {
   "title": "Addresses Not Ready",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 19 },
   "targets": [
    {
     "expr": "enmasse_addresses_not_ready_total"
    }
   ]
  }
 ]
}