---
- name: Create secret with the keycloak credentials
  shell: oc create secret generic -n {{ namespace }} keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password={{ keycloak_admin_password }}
  register: secret_exists
  failed_when: secret_exists.stderr != '' and 'already exists' not in secret_exists.stderr
- name: Label secret
  shell: oc label secret keycloak-credentials -n {{ namespace }} app=enmasse
  when: secret_exists.rc == 0
- name: check if keycloak deployment already exists
  shell: oc get deployment keycloak -n {{ namespace }}
  register: keycloak_exists
  failed_when: keycloak_exists.stderr != '' and 'not found' not in keycloak_exists.stderr
- name: Apply the Standard Authentication Service configuration
  shell:
    cmd: |
      cat <<EOF | oc apply -f -
      apiVersion: admin.enmasse.io/v1beta1
      kind: AuthenticationService
      metadata:
        name: standard-authservice
        labels:
          app: enmasse
      spec:
        type: standard
        standard:
          routeName: keycloak
          serviceName: standard-authservice
          deploymentName: keycloak
          credentialsSecret:
            name: keycloak-credentials
          storage:
            type: persistent-claim
            claimName: keycloak-data
            size: 1Gi
      EOF
  when: keycloak_exists.rc != 0
