kind: Deployment
apiVersion: apps/v1
metadata:
  name: enmasse-operator
  labels:
    app: enmasse
    name: enmasse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: enmasse-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: enmasse-operator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.enmasse.io/operator-infra
                    operator: In
                    values:
                      - "true"
      serviceAccountName: enmasse-operator
      containers:
      - name: controller
        image: registry.redhat.io/amq7/amq-online-1-controller-manager:1.3
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "enmasse-operator"
        - name: IMAGE_PULL_POLICY
          value: "Always"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        - name: CONTROLLER_ENABLE_IOT_CONFIG
          value: "true"
        - name: CONTROLLER_ENABLE_AUTHENTICATION_SERVICE
          value: "true"
        - name: CONTROLLER_MANAGER_IMAGE
          value: registry.redhat.io/amq7/amq-online-1-controller-manager:1.3
        - name: IOT_AUTH_SERVICE_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-auth-service:1.3
        - name: IOT_DEVICE_REGISTRY_FILE_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-device-registry-file:1.3
        - name: IOT_DEVICE_REGISTRY_INFINISPAN_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-device-registry-datagrid:1.3
        - name: IOT_GC_IMAGE
          value: 
        - name: IOT_HTTP_ADAPTER_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-http-adapter:1.3
        - name: IOT_MQTT_ADAPTER_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-mqtt-adapter:1.3
        - name: IOT_LORAWAN_ADAPTER_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-lorawan-adapter-rhel7:1.3
        - name: IOT_SIGFOX_ADAPTER_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-sigfox-adapter-rhel7:1.3
        - name: IOT_TENANT_SERVICE_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-tenant-service:1.3
        - name: IOT_PROXY_CONFIGURATOR_IMAGE
          value: registry.redhat.io/amq7-tech-preview/amq-online-1-iot-proxy-configurator:1.3
        - name: ROUTER_IMAGE
          value: registry.redhat.io/amq7/amq-interconnect:1.6
        - name: NONE_AUTHSERVICE_IMAGE
          value: registry.redhat.io/amq7/amq-online-1-none-auth-service:1.3
        - name: KEYCLOAK_IMAGE
          value: registry.redhat.io/redhat-sso-7/sso73-openshift:latest
        - name: KEYCLOAK_PLUGIN_IMAGE
          value: registry.redhat.io/amq7/amq-online-1-auth-plugin:1.3
        - name: CONTROLLER_ENABLE_CONSOLE_SERVICE
          value: "true"
        - name: CONSOLE_INIT_IMAGE
          value: "registry.redhat.io/amq7/amq-online-1-console-init:1.3"
        - name: CONSOLE_PROXY_OPENSHIFT_IMAGE
          value: "registry.redhat.io/openshift3/oauth-proxy:latest"
        - name: CONSOLE_PROXY_KUBERNETES_IMAGE
          value: "quay.io/pusher/oauth2_proxy:latest"
        - name: CONSOLE_HTTPD_IMAGE
          value: "registry.redhat.io/amq7/amq-online-1-console-httpd:1.3"
