apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: enmasse
  name: addressspaceplans.admin.enmasse.io
spec:
  conversion:
    strategy: None
  group: admin.enmasse.io
  names:
    categories:
      - enmasse
    kind: AddressSpacePlan
    listKind: AddressSpacePlanList
    plural: addressspaceplans
    singular: addressspaceplan
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The phase of the address space plan
          jsonPath: .status.phase
          name: Phase
          type: string
        - description: The status of the address space plan
          jsonPath: .status.message
          name: Status
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta2
      schema:
        openAPIV3Schema:
          description: AddressSpacePlan describes the allowed resource usage of an address space. This resource is created by the service administrator.
          properties:
            addressPlans:
              items:
                type: string
              type: array
            addressSpaceType:
              type: string
            displayName:
              type: string
            displayOrder:
              type: integer
            longDescription:
              type: string
            resources:
              items:
                properties:
                  max:
                    type: number
                  name:
                    type: string
                required:
                  - name
                  - max
                type: object
              type: array
            shortDescription:
              type: string
            spec:
              properties:
                addressPlans:
                  items:
                    type: string
                  type: array
                addressSpaceType:
                  type: string
                displayName:
                  type: string
                displayOrder:
                  type: integer
                infraConfigRef:
                  type: string
                longDescription:
                  type: string
                resourceLimits:
                  properties:
                    aggregate:
                      type: number
                    broker:
                      type: number
                    router:
                      type: number
                  type: object
                shortDescription:
                  type: string
              required:
                - addressSpaceType
                - resourceLimits
                - addressPlans
                - infraConfigRef
              type: object
            status:
              properties:
                message:
                  description: Status and error messages for the address space plan.
                  type: string
                phase:
                  description: Phase of the address space plan.
                  type: string
              type: object
            uuid:
              type: string
          type: object
      served: true
      storage: true
    - additionalPrinterColumns:
        - description: The phase of the address space plan
          jsonPath: .status.phase
          name: Phase
          type: string
        - description: The status of the address space plan
          jsonPath: .status.message
          name: Status
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          description: AddressSpacePlan describes the allowed resource usage of an address space. This resource is created by the service administrator.
          properties:
            addressPlans:
              items:
                type: string
              type: array
            addressSpaceType:
              type: string
            displayName:
              type: string
            displayOrder:
              type: integer
            longDescription:
              type: string
            resources:
              items:
                properties:
                  max:
                    type: number
                  name:
                    type: string
                required:
                  - name
                  - max
                type: object
              type: array
            shortDescription:
              type: string
            spec:
              properties:
                addressPlans:
                  items:
                    type: string
                  type: array
                addressSpaceType:
                  type: string
                displayName:
                  type: string
                displayOrder:
                  type: integer
                infraConfigRef:
                  type: string
                longDescription:
                  type: string
                resourceLimits:
                  properties:
                    aggregate:
                      type: number
                    broker:
                      type: number
                    router:
                      type: number
                  type: object
                shortDescription:
                  type: string
              required:
                - addressSpaceType
                - resourceLimits
                - addressPlans
                - infraConfigRef
              type: object
            status:
              properties:
                message:
                  description: Status and error messages for the address space plan.
                  type: string
                phase:
                  description: Phase of the address space plan.
                  type: string
              type: object
            uuid:
              type: string
          type: object
      served: true
      storage: false
    - additionalPrinterColumns:
        - description: The phase of the address space plan
          jsonPath: .status.phase
          name: Phase
          type: string
        - description: The status of the address space plan
          jsonPath: .status.message
          name: Status
          priority: 1
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: AddressSpacePlan describes the allowed resource usage of an address space. This resource is created by the service administrator.
          properties:
            addressPlans:
              items:
                type: string
              type: array
            addressSpaceType:
              type: string
            displayName:
              type: string
            displayOrder:
              type: integer
            longDescription:
              type: string
            resources:
              items:
                properties:
                  max:
                    type: number
                  name:
                    type: string
                required:
                  - name
                  - max
                type: object
              type: array
            shortDescription:
              type: string
            spec:
              properties:
                addressPlans:
                  items:
                    type: string
                  type: array
                addressSpaceType:
                  type: string
                displayName:
                  type: string
                displayOrder:
                  type: integer
                infraConfigRef:
                  type: string
                longDescription:
                  type: string
                resourceLimits:
                  properties:
                    aggregate:
                      type: number
                    broker:
                      type: number
                    router:
                      type: number
                  type: object
                shortDescription:
                  type: string
              required:
                - addressSpaceType
                - resourceLimits
                - addressPlans
                - infraConfigRef
              type: object
            status:
              properties:
                message:
                  description: Status and error messages for the address space plan.
                  type: string
                phase:
                  description: Phase of the address space plan.
                  type: string
              type: object
            uuid:
              type: string
          type: object
      served: true
      storage: false
