apiVersion: v1
kind: Template
metadata:
  name: address
  labels:
    app: enmasse
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${ADDRESS_SPACE_NAMESPACE}.${ADDRESS_SPACE}.${ADDRESS}
      labels:
        type: address-config
        infraUuid: ${INFRA_UUID}
        app: enmasse
    data:
      config.json: |-
        {
          "apiVersion": "enmasse.io/v1",
          "kind": "Address",
          "metadata": {
            "name": "${ADDRESS_SPACE}.${ADDRESS}",
            "namespace": "${ADDRESS_SPACE_NAMESPACE}"
          },
          "spec": {
            "address": "${ADDRESS}",
            "type": "${TYPE}",
            "plan": "${PLAN}"
          }
        }
parameters:
  - name: ADDRESS
    description: Address
    required: true
  - name: ADDRESS_SPACE_NAMESPACE
    description: Namespace of address and address space
    required: true
  - name: INFRA_UUID
    description: Infrastructure uuid
    required: true
  - name: ADDRESS_SPACE
    description: Address space of address
    required: true
  - name: TYPE
    description: Type of address
    required: true
  - name: PLAN
    description: Plan to use for address
    required: true
