apiVersion: admin.enmasse.io/v1alpha1
kind: StandardInfraConfig
metadata:
  name: default
  labels:
    app: enmasse
spec:
  version: 0.24.0.jbossorg-3
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 512Mi
      storage: 2Gi
    addressFullPolicy: FAIL
  router:
    resources:
      memory: 512Mi
    linkCapacity: 250
