#!/bin/bash -ex
# Render templates (render_templates executable found in operator's dist-git
# repo) is customers code which works with a set of environment variables
# exposed by the operator code in CPaaS (part of the operator build).

test_exposed_vars() {
    # Test container components corresponding vars are correctly exposed
    local -a components suffixes missing_vars
    # To add more components to the list, make sure they exists in both widget
    # repo and product used in CI (part of service repo)
    components=("controller-manager")
    # In CPaaS we export each container component with the following suffixes
    suffixes=("IMAGE_PULL_URL" "BUILD_INFO_JSON")
    local component normalized suffix

    for component in "${components[@]}"; do
        # normalize container name, all upper case and underscores instead of
        # hyphens (e.g a-b-c -> A_B_C)
        normalized=$(echo "${component^^}" | tr '-' '_')
        for suffix in "${suffixes[@]}"; do
            [[ -v "${normalized}_${suffix}" ]] || {
                missing_vars+=("${normalized}_${suffix}")
            }
        done
    done

    [[ "${#missing_vars[@]}" -eq 0 ]] || {
        echo "ERROR: Expected variables not set: ${missing_vars[*]}" >&2
        return 1
    }
}

main() {
    test_exposed_vars
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && {
    main
}