apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-small-queue
  labels:
    app: enmasse
spec:
  displayName: Small Queue
  displayOrder: 0
  shortDescription: Creates a small queue sharing underlying broker with other queues.
  longDescription: Creates a small queue sharing underlying broker with other queues.
  addressType: queue
  resources:
    router: 0.001
    broker: 0.01
