apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-large-queue
  labels:
    app: enmasse
spec:
  displayName: Large Queue
  displayOrder: 2
  shortDescription: Creates a large queue backed by a dedicated broker.
  longDescription: Creates a large queue backed by a dedicated broker.
  addressType: queue
  resources:
    router: 0.1
    broker: 1.0
