apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: standard-small
  labels:
    app: enmasse
spec:
  displayName: Small
  displayOrder: 0
  infraConfigRef: default-minimal
  shortDescription: Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis
  longDescription: Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis. This plan allows up to 1 router and 1 broker in total, and is suitable for small applications using small address plans and few addresses.
  addressSpaceType: standard
  resourceLimits:
    router: 1.0
    broker: 1.0
    aggregate: 2.0
  addressPlans:
  - standard-small-anycast
  - standard-medium-anycast
  - standard-large-anycast
  - standard-small-multicast
  - standard-medium-multicast
  - standard-large-multicast
  - standard-small-queue
  - standard-medium-queue
  - standard-large-queue
  - standard-small-topic
  - standard-medium-topic
  - standard-large-topic
  - standard-small-subscription
  - standard-medium-subscription
  - standard-large-subscription
  - standard-deadletter
