apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-small-multicast
  labels:
    app: enmasse
spec:
  displayName: Small Multicast
  displayOrder: 0
  shortDescription: Creates a small multicast address.
  longDescription: Creates a small multicast address where messages go via a router that does not take ownership of the messages.
  addressType: multicast
  resources:
    router: 0.001
