apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-xlarge-queue
  labels:
    app: enmasse
spec:
  displayName: Extra Large Queue
  displayOrder: 3
  shortDescription: Creates an extra large queue backed by 2 brokers.
  longDescription: Creates an extra large queue backed by 2 brokers.
  addressType: queue
  resources:
    router: 0.2
    broker: 2.0
