- name: Create the standard authentication service service
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/sso/service.yaml
- name: Create the standard authentication service deployment
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/sso/keycloak-deployment.yaml
- name: Create the standard authentication service persistent volume claim
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/sso/pvc.yaml
- name: Create the standard authentication service route
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/sso/route.yaml

- name: Create the standard authentication service database service
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/sso/postgresql-service.yaml
- name: Create the standard authentication service database deployment
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/sso/postgresql-deployment.yaml
- name: Create the standard authentication service database persistent volume claim
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/sso/postgresql-pvc.yaml

- name: Check if postgresql secret exists
  shell: oc get secret -n {{ namespace }} postgresql
  register: secret_exists 
  ignore_errors: True
- name: Create secret with the postgresql info
  when: secret_exists.failed and (postgresql_db_name is defined) and (postgresql_db_username is defined) and (postgresql_db_password is defined) 
  shell: oc create secret generic -n {{ namespace }} postgresql --from-literal=database-name={{ postgresql_db_name }} --from-literal=database-user={{ postgresql_db_username }} --from-literal=database-password={{ postgresql_db_password }}
