apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: enmasse
  name: enmasse.io:console-server
rules:
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addressspaces", "addresses", "addressspaceschemas" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch" ]
