apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "console-server"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:console-server
subjects:
- kind: ServiceAccount
  name: console-server
  namespace: amq-online-infra
