apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:standard-authservice-amq-online-infra"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:standard-authservice
subjects:
- kind: ServiceAccount
  name: standard-authservice
  namespace: amq-online-infra
